# Week 02 Lab Assigment: Image Processing Through a Four-Step Pipeline

**Course:** Perceptual Computing / Computer Graphics and Human-Computer Interaction  
**Coverage:** Week 1-3 lecture material  
**Work mode:** Individual submission

## Student Information

- **Name:** _Sarfraz Ali Zardari_
- **Roll number:** _2K24/AIE/56_
- **GitHub username:**  2K24AIE56.
- **GitHub repository:**  CGHCI.

 

In [6]:
def rgb_to_grayscale(r, g, b):
    luminosity = 0.299 * r + 0.587 * g + 0.114 * b
    return int(round(luminosity))


# Example RGB values
r = 180
g = 120
b = 60

result = rgb_to_grayscale(r, g, b)

print("RGB:", r, g, b)
print("Grayscale value:", result)

RGB: 180 120 60
Grayscale value: 131


In [7]:
import numpy as np

def adjust_brightness_contrast(image, alpha, beta):
    # Formula: O = alpha * I + beta
    image_float = image.astype(np.float32)

    adjusted = alpha * image_float + beta

    # Value ko 0 se 255 ke darmiyan rakhna
    adjusted = np.clip(adjusted, 0, 255)

    return adjusted.astype(np.uint8)


# Sample image
image = np.array([
    [100, 150],
    [200, 50]
], dtype=np.uint8)

# Brightness and contrast adjust
alpha = 1.5
beta = -20

result = adjust_brightness_contrast(image, alpha, beta)

print("Original Image:")
print(image)

print("\nAdjusted Image:")
print(result)

Original Image:
[[100 150]
 [200  50]]

Adjusted Image:
[[130 205]
 [255  55]]


In [8]:
import numpy as np

# Grayscale image ko black and white mein convert karna
def threshold_image(image, threshold):
    result = np.where(image >= threshold, 255, 0)
    return result.astype(np.uint8)


# Input image
problem_1_input = np.array([
    [20, 128, 200],
    [100, 150, 250]
], dtype=np.uint8)

# Function call
result = threshold_image(problem_1_input, 128)

print("Original Image:")
print(problem_1_input)

print("\nThreshold Image:")
print(result)

# Test
problem_1_expected = np.array([
    [0, 255, 255],
    [0, 255, 255]
], dtype=np.uint8)

np.testing.assert_array_equal(result, problem_1_expected)

print("\nProblem 1 passed.")

Original Image:
[[ 20 128 200]
 [100 150 250]]

Threshold Image:
[[  0 255 255]
 [  0 255 255]]

Problem 1 passed.


In [9]:
# Image ki memory bytes mein calculate karna
def display_memory_bytes(width, height, bpp):
    # Formula: width × height × bits per pixel ÷ 8
    memory_bytes = width * height * bpp // 8
    return memory_bytes


# Test values
width = 1920
height = 1080
bpp = 24

# Function call
result = display_memory_bytes(width, height, bpp)

print("Width:", width)
print("Height:", height)
print("Bits per pixel:", bpp)
print("Memory required:", result, "bytes")


# Test
expected_bytes = 1920 * 1080 * 24 // 8

assert result == expected_bytes

print("Problem 2 passed.")

Width: 1920
Height: 1080
Bits per pixel: 24
Memory required: 6220800 bytes
Problem 2 passed.


In [10]:
import numpy as np

# 3x3 pixels ka average calculate karna
def mean_filter_3x3(neighborhood):
    total = np.sum(neighborhood)
    average = total / 9

    return int(round(average))


# Input 3x3 image
problem_3_input = np.array([
    [10, 20, 10],
    [30, 50, 30],
    [10, 20, 10]
], dtype=np.uint8)


# Function call
result = mean_filter_3x3(problem_3_input)

print("3x3 Neighborhood:")
print(problem_3_input)

print("\nMean value:", result)


# Test
assert result == 21

print("Problem 3 passed.")

3x3 Neighborhood:
[[10 20 10]
 [30 50 30]
 [10 20 10]]

Mean value: 21
Problem 3 passed.


In [11]:
import numpy as np

# Image values ko ek range se doosri range mein convert karna
def contrast_stretch(
    image,
    in_min,
    in_max,
    out_min=0.0,
    out_max=255.0
):
    # Contrast stretching formula
    stretched = (
        (image - in_min)
        * (out_max - out_min)
        / (in_max - in_min)
        + out_min
    )

    # Values ko output range mein rakhna
    return np.clip(stretched, out_min, out_max)


# Input image
problem_4_input = np.array([50, 100, 150], dtype=np.float32)

# Function call
result = contrast_stretch(problem_4_input, 50, 150)

print("Original values:")
print(problem_4_input)

print("\nContrast stretched values:")
print(result)


# Test
expected = np.array([0.0, 127.5, 255.0], dtype=np.float32)

np.testing.assert_allclose(result, expected)

print("\nProblem 4 passed.")

Original values:
[ 50. 100. 150.]

Contrast stretched values:
[  0.  127.5 255. ]

Problem 4 passed.


In [12]:
import numpy as np

# Sobel calculation
def sobel_response(block):
    # X direction kernel
    gx_kernel = np.array([
        [-1, 0, 1],
        [-2, 0, 2],
        [-1, 0, 1]
    ], dtype=np.float32)

    # Y direction kernel
    gy_kernel = np.array([
        [-1, -2, -1],
        [0, 0, 0],
        [1, 2, 1]
    ], dtype=np.float32)

    # Kernel aur image block ko multiply karke sum
    gx = np.sum(gx_kernel * block)
    gy = np.sum(gy_kernel * block)

    # Edge strength
    strength = np.sqrt(gx**2 + gy**2)

    return float(gx), float(gy), float(strength)


# Input 3x3 block
problem_5_input = np.array([
    [20, 20, 200],
    [20, 20, 200],
    [20, 20, 200]
], dtype=np.float32)


# Function call
gx, gy, strength = sobel_response(problem_5_input)

print("Gx:", gx)
print("Gy:", gy)
print("Edge Strength:", strength)


# Test
assert gx == 720.0 and gy == 0.0

print("Problem 5 passed.")

Gx: 720.0
Gy: 0.0
Edge Strength: 720.0
Problem 5 passed.
